--------------------------------------------------------
--  파일이 생성됨 - 일요일-4월-06-2025   
--------------------------------------------------------
REM INSERTING into ADMIN.STUDENT
SET DEFINE OFF;
Insert into ADMIN.STUDENT (ID,NAME,CLASS,TEACHER,KOREAN,ENGLISH,MATH,SCIENCE,HISTORY) values (1,'김영수',1,'박용철',60,70,80,45,75);
Insert into ADMIN.STUDENT (ID,NAME,CLASS,TEACHER,KOREAN,ENGLISH,MATH,SCIENCE,HISTORY) values (2,'이민호',1,'박용철',75,85,90,55,80);
Insert into ADMIN.STUDENT (ID,NAME,CLASS,TEACHER,KOREAN,ENGLISH,MATH,SCIENCE,HISTORY) values (3,'박지훈',1,'박용철',65,78,82,50,72);
Insert into ADMIN.STUDENT (ID,NAME,CLASS,TEACHER,KOREAN,ENGLISH,MATH,SCIENCE,HISTORY) values (4,'정수빈',1,'박용철',80,88,95,60,85);
Insert into ADMIN.STUDENT (ID,NAME,CLASS,TEACHER,KOREAN,ENGLISH,MATH,SCIENCE,HISTORY) values (5,'최은지',1,'박용철',58,67,77,42,68);
Insert into ADMIN.STUDENT (ID,NAME,CLASS,TEACHER,KOREAN,ENGLISH,MATH,SCIENCE,HISTORY) values (6,'한예지',2,'김상훈',70,75,85,50,78);
Insert into ADMIN.STUDENT (ID,NAME,CLASS,TEACHER,KOREAN,ENGLISH,MATH,SCIENCE,HISTORY) values (7,'김도윤',2,'김상훈',82,90,88,65,85);
Insert into ADMIN.STUDENT (ID,NAME,CLASS,TEACHER,KOREAN,ENGLISH,MATH,SCIENCE,HISTORY) values (8,'유진석',2,'김상훈',60,72,80,45,70);
Insert into ADMIN.STUDENT (ID,NAME,CLASS,TEACHER,KOREAN,ENGLISH,MATH,SCIENCE,HISTORY) values (9,'서지우',2,'김상훈',55,60,65,38,60);
Insert into ADMIN.STUDENT (ID,NAME,CLASS,TEACHER,KOREAN,ENGLISH,MATH,SCIENCE,HISTORY) values (10,'오지현',2,'김상훈',78,85,92,55,82);
Insert into ADMIN.STUDENT (ID,NAME,CLASS,TEACHER,KOREAN,ENGLISH,MATH,SCIENCE,HISTORY) values (11,'강민혁',3,'이서준',85,90,95,70,88);
Insert into ADMIN.STUDENT (ID,NAME,CLASS,TEACHER,KOREAN,ENGLISH,MATH,SCIENCE,HISTORY) values (12,'배준호',3,'이서준',62,68,75,50,65);
Insert into ADMIN.STUDENT (ID,NAME,CLASS,TEACHER,KOREAN,ENGLISH,MATH,SCIENCE,HISTORY) values (13,'문지훈',3,'이서준',73,78,85,55,75);
Insert into ADMIN.STUDENT (ID,NAME,CLASS,TEACHER,KOREAN,ENGLISH,MATH,SCIENCE,HISTORY) values (14,'신유나',3,'이서준',80,88,90,60,82);
Insert into ADMIN.STUDENT (ID,NAME,CLASS,TEACHER,KOREAN,ENGLISH,MATH,SCIENCE,HISTORY) values (15,'조하영',3,'이서준',67,73,80,48,70);
